{% set name = "perl-b-hooks-endofscope" %}
{% set version = "0.28" %}
{% set sha256 = "edac77a17fc36620c8324cc194ce1fad2f02e9fcbe72d08ad0b2c47f0c7fd8ef" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/B-Hooks-EndOfScope-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 2
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-sub-exporter-progressive
    - perl-module-implementation
    - perl-variable-magic
  run:
    - perl

test:
  imports:
    - B::Hooks::EndOfScope
    - B::Hooks::EndOfScope::PP
    - B::Hooks::EndOfScope::XS

about:
  home: https://github.com/karenetheridge/B-Hooks-EndOfScope
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file: LICENCE
  summary: 'Execute code after a scope finished compilation'

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
